// const { Middleware } = require('swagger-express-middleware');
const Ajv = require('ajv');
const addFormats = require('ajv-formats');

const http = require('http');
const fs = require('fs');
const path = require('path');
const swaggerUI = require('swagger-ui-express');
const jsYaml = require('js-yaml');
const express = require('express');
const cors = require('cors');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const OpenApiValidator = require('express-openapi-validator');
const logger = require('./logger');
const config = require('./config');

function loadOpenApiSpec(openApiYamlPath) {
  const raw = fs.readFileSync(openApiYamlPath, 'utf8');
  return jsYaml.safeLoad(raw);
}

function getWeatherSchema(spec) {
  const schema = spec?.components?.schemas?.Weather;
  if (!schema) throw new Error("Weather schema not found");
  return schema;
}


class ExpressServer {
  constructor(port, openApiYaml) {
    this.port = port;
    this.app = express();
    this.openApiPath = openApiYaml;
    try {
      this.schema = jsYaml.safeLoad(fs.readFileSync(openApiYaml));
    } catch (e) {
      logger.error('failed to start Express Server', e.message);
    }
    this.setupMiddleware();
  }

  setupMiddleware() {
    // this.setupAllowedMedia();
    this.app.use(cors());
    this.app.use(bodyParser.json({ limit: '14MB' }));
    this.app.use(express.json());
    this.app.use(express.urlencoded({ extended: false }));
    this.app.use(cookieParser());


    const spec = loadOpenApiSpec(this.openApiPath);
    const weatherSchema = getWeatherSchema(spec);

    const ajv = new Ajv({ allErrors: true, strict: false });
    addFormats(ajv);

    const validateWeather = ajv.compile(weatherSchema);

    const weatherValidateMw = (req, res, next) => {
      const ok = validateWeather(req.body);

      const t = req.body?.temperature;
      if (ok && typeof t === 'number' && (t < -60 || t > 60)) {
        return res.status(400).json({
          error: "VALIDATION_FAILED",
          message: "temperature must be between -60 and 60",
          details: [{ path: "/temperature", message: "out of allowed range" }]
        });
      }

      if (!ok) {
        return res.status(400).json({
          error: "VALIDATION_FAILED",
          message: "Invalid weather payload",
          details: (validateWeather.errors || []).map(e => ({
            path: e.instancePath || e.schemaPath,
            message: e.message
          }))
        });
      }

      next();
    };

    this.app.post('/weather', weatherValidateMw);


    // Simple test to see that the server is up and responding
    this.app.get('/hello', (req, res) => res.send(`Hello World. path: ${this.openApiPath}`));
    // Send the openapi document *AS GENERATED BY THE GENERATOR*
    this.app.get('/openapi', (req, res) => res.sendFile((path.join(__dirname, 'api', 'openapi.yaml'))));
    // View the openapi document in a visual interface. Should be able to test from this page
    this.app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(this.schema));
    this.app.get('/login-redirect', (req, res) => {
      res.status(200);
      res.json(req.query);
    });
    this.app.get('/oauth2-redirect.html', (req, res) => {
      res.status(200);
      res.json(req.query);
    });
    this.app.use(
      OpenApiValidator.middleware({
        apiSpec: this.openApiPath,
        operationHandlers: path.join(__dirname),
        fileUploader: { dest: config.FILE_UPLOAD_PATH },

        validateRequests: false 
      }),
    );
  }

  launch() {
    // eslint-disable-next-line no-unused-vars
    this.app.use((err, req, res, next) => {
      // format errors
      res.status(err.status || 500).json({
        message: err.message || err,
        errors: err.errors || '',
      });
    });

    http.createServer(this.app).listen(this.port);
    console.log(`Listening on port ${this.port}`);
  }

  async close() {
    if (this.server !== undefined) {
      await this.server.close();
      console.log(`Server on port ${this.port} shut down`);
    }
  }
}

module.exports = ExpressServer;
